version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.06
    steps:
      # ... steps for building/testing app ...
      - setup_remote_docker:
          version: 20.10.14

    steps:
      - checkout
#      - setup_remote_docker:
 #         version: 20.10.5

      # Build your Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t myfirstimage:latest .

      # Push the Docker image to a container registry
      - run:
          name: Push Docker image
          command: |
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g5u9i3i2
            docker tag circleci:latest public.ecr.aws/g5u9i3i2/circleci:latest
            docker push public.ecr.aws/g5u9i3i2/circleci:latest
